# 1 Assignment 4

In [1]:
import os
import os
import pickle
import pandas as pd
import numpy as np
import urllib.request

1. Import the `REC0111.sav`, `RE223132.sav` and `RE516171.sav` files and their variables and values labels from this path `"../../_data/endes/2019"`. The name of imported files should be named as `rec_1`, `rec_2` and `rec_3` for files `REC0111.sav`, `RE223132.sav` and `RE516171.sav` respectively. The name of the variable and value labels should be `var_labels1` and `value_labels1` for `rec1`, `var_labels2` and `value_labels2` for `rec2`, and `var_labels3` and `value_labels3` for `rec3`. **Hint: See the section 3.3.4 of [the lecture 3](https://github.com/alexanderquispe/Diplomado_PUCP/blob/main/Lecture_3/Lecture_3.ipynb)**

In [2]:
#%pip install pyreadstat
import pyreadstat
import pandas as pd

rec_1 = pd.read_spss(r"../../_data/endes/2019/REC0111.sav")
rec_2 = pd.read_spss(r"../../_data/endes/2019/RE223132.sav")
rec_3 = pd.read_spss(r"../../_data/endes/2019/RE516171.sav")

In [3]:
import pyreadstat

file_paths = [
    "../../_data/endes/2019/REC0111.sav",
    "../../_data/endes/2019/RE223132.sav",
    "../../_data/endes/2019/RE516171.sav"
]

var_labels = {}
value_labels = {}

for file_path in file_paths:
    df, meta = pyreadstat.read_sav(file_path, apply_value_formats=True)

    # Extract variable labels
    if isinstance(meta.column_labels, list):
        var_labels[file_path] = {col: label for col, label in zip(df.columns, meta.column_labels)}
    else:
        var_labels[file_path] = meta.column_labels

    # Extract value labels
    value_labels[file_path] = meta.variable_value_labels

# Access variable and value labels for each file
var_labels1 = var_labels["../../_data/endes/2019/REC0111.sav"]
var_labels2 = var_labels["../../_data/endes/2019/RE223132.sav"]
var_labels3 = var_labels["../../_data/endes/2019/RE516171.sav"]

value_labels1 = value_labels["../../_data/endes/2019/REC0111.sav"]
value_labels2 = value_labels["../../_data/endes/2019/RE223132.sav"]
value_labels3 = value_labels["../../_data/endes/2019/RE516171.sav"]

2. Select the following columns for each data set:
|Data|Columns|
|---|---|
|rec1| CASEID, V000, V001, V002, V003, V004, V007, V008, V009, V010, V011, V012, V024, V102, V120, V121, V122, V123, V124, V125, V127, V133 |
|rec2| CASEID, V201, V218, V301, V302, V323, V323A, V325A, V326, V327, V337, V359, V360, V361, V362, V363, V364, V367, V372, V372A, V375A, V376, V376A, V379, V380 |
|rec3| CASEID, V501, V502, V503, V504, V505, V506, V507, V508, V509, V510, V511, V512, V513, V525, V613, V714, V715 |


Additioanlly, you should update the variables and value labels objects. They must have information only for the selected columns. The new dataframes should be name as `rec1_1`, `rec2_1`, and `rec3_1`. The new varible labels objects should be named as `new_var_labels1`, `new_var_labels2`, and `new_var_labels3`. The new value labels objects should be named as `new_value_labels1`, `new_value_labels2`, and `new_value_labels3` **Hint: Use the `loc` and column names to filter, `for loop`,   and [this link](https://stackoverflow.com/questions/3420122/filter-dict-to-contain-only-certain-keys) to update the var and value dictionary.**

In [4]:
# Define the selected columns for each rec
selected_columns_rec = [
    ['CASEID', 'V000', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008', 'V009', 'V010', 'V011', 'V012', 'V024', 'V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127', 'V133'],
    ['CASEID', 'V201', 'V218', 'V301', 'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327', 'V337', 'V359', 'V360', 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A', 'V375A', 'V376', 'V376A', 'V379', 'V380'],
    ['CASEID', 'V501', 'V502', 'V503', 'V504', 'V505', 'V506', 'V507', 'V508', 'V509', 'V510', 'V511', 'V512', 'V513', 'V525', 'V613', 'V714', 'V715']
]

# Iterate through the selected columns and perform the operations
rec_list = [rec_1, rec_2, rec_3]
new_var_labels_list = [var_labels1, var_labels2, var_labels3]
new_value_labels_list = [value_labels1, value_labels2, value_labels3]

for i in range(3):
    # Update rec_i with selected columns
    rec_i = rec_list[i].loc[:, selected_columns_rec[i]]

    # Update variable labels for rec_i
    new_var_labels_i = {key: value for key, value in new_var_labels_list[i].items() if key in selected_columns_rec[i]}

    # Update value labels for rec_i
    new_value_labels_i = {key: value for key, value in new_value_labels_list[i].items() if key in selected_columns_rec[i]}
    
    if i == 0:
        rec1_1 = rec_i
        new_var_labels1 = new_var_labels_i
        new_value_labels1 = new_value_labels_i
    elif i == 1:
        rec2_1 = rec_i
        new_var_labels2 = new_var_labels_i
        new_value_labels2 = new_value_labels_i
    elif i == 2:
        rec3_1 = rec_i
        new_var_labels3 = new_var_labels_i
        new_value_labels3 = new_value_labels_i

3. Generate a new column for `rec1_1` named as `year`. It should be equal to `2019`. Also, you must update this new variable for the `var_labels` dictionary. Generate a new key for `new_var_labels1` and the value for this key should be **"Year of the survey"** **Hint: Use `loc` and `update` method.**

In [5]:
# Generate a new column 'year' with the value 2019 using loc
rec1_1.loc[:, 'year'] = 2019

# Update var_labels1 dictionary using the update method
new_var_labels1.update({'year': 'Year of the survey'})

4. Merge `rec1_1`, `rec2_1`, and `rec3_1` using **CASEID**. Name this new object as `endes_2019`. **Hint: Use [this link](https://stackoverflow.com/questions/53645882/pandas-merging-101)**

In [6]:
# Merge rec1_1, rec2_1, and rec3_1 using CASEID
endes_2019 = rec1_1.merge(rec2_1, on='CASEID').merge(rec3_1, on='CASEID')

5. Unify all the `new_var_labels` in one object and `new_value_labels` in another one object. Name these two objects as `var_labels` and `value_labels`. Use them to generate new attributes for `endes_2019`. These attributes should be named as `var_labels` and `value_labels`. **Hint: Use `update` method.**

In [7]:
# Unify new_var_labels and new_value_labels into var_labels and value_labels
var_labels = {}
value_labels = {}

# Update var_labels and value_labels with the dictionaries from each rec dataframe
var_labels.update(new_var_labels1)
var_labels.update(new_var_labels2)
var_labels.update(new_var_labels3)

value_labels.update(new_value_labels1)
value_labels.update(new_value_labels2)
value_labels.update(new_value_labels3)

# Generate new attributes for endes_2019
endes_2019['var_labels'] = var_labels
endes_2019['value_labels'] = value_labels

6. Now, replicate your code of the prevoius sections but for years **2019, 2018, 2017, 2016, 2015**. Import the `REC0111.sav`, `RE223132.sav` and `RE516171.sav` files and their **variables and values labels** from this path `"../../_data/endes/"`. For this excersie you must use a for loop. This loop must iterate over **2019, 2018, 2017, 2016, 2015 folders** and import these files. All the files have the same name. You must store these files and their labels in a nested dictionary named as `all_data`. The keys of the dictionary should be named as `year_2019`, for example, and the keys of the nested dictionary should be `data`, `var_labels`, and `value_labels`. **Hint: Use [this link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=4d6de78e00e7001f16bf6473c2eb7ce24fb611cd&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f346436646537386530306537303031663136626636343733633265623763653234666236313163642f4c6563747572655f342f4c6563747572655f342e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_4%2FLecture_4.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=95#4.2.)**

In [8]:
import os
import pandas as pd
from scipy.io import savemat

# Initialize the nested dictionary
all_data = {}

# Specify the years
years = [2019, 2018, 2017, 2016, 2015]

# Specify the filenames
filenames = ["REC0111.sav", "RE223132.sav", "RE516171.sav"]

# Define the selected columns for each rec
selected_columns_rec = [
    ['CASEID', 'V000', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008', 'V009', 'V010', 'V011', 'V012', 'V024', 'V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127', 'V133'],
    ['CASEID', 'V201', 'V218', 'V301', 'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327', 'V337', 'V359', 'V360', 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A', 'V375A', 'V376', 'V376A', 'V379', 'V380'],
    ['CASEID', 'V501', 'V502', 'V503', 'V504', 'V505', 'V506', 'V507', 'V508', 'V509', 'V510', 'V511', 'V512', 'V513', 'V525', 'V613', 'V714', 'V715']
]

# Iterate through each year
for year in years:
    # Initialize a dictionary for the current year
    year_data = {}

    # Loop through each filename for the current year
    for filename in filenames:
        # Construct the file path
        file_path = f"../../_data/endes/{year}/{filename}"

        # Check if the file exists
        if os.path.exists(file_path):
            # Load data from the .sav file
            data = pd.read_spss(file_path)

            # Check for the existence of selected columns
            selected_columns = [col for col in selected_columns_rec[filenames.index(filename)] if col in data.columns]

            # Select the desired columns
            rec_i = data.loc[:, selected_columns]

            # Add a new column 'year' with the value of the current year
            rec_i['year'] = year

            # Update variable labels for rec_i
            new_var_labels_i = {key: value for key, value in new_var_labels_list[filenames.index(filename)].items() if key in selected_columns}

            # Update value labels for rec_i
            new_value_labels_i = {key: value for key, value in new_value_labels_list[filenames.index(filename)].items() if key in selected_columns}

            # Store data, var_labels, and value_labels in a nested dictionary
            file_key = f"{os.path.splitext(filename)[0]}_{year}"
            year_data[file_key] = {
                'data': rec_i,
                'var_labels': new_var_labels_i,
                'value_labels': new_value_labels_i
            }
        else:
            print(f"File not found: {file_path}")

    # Store the data for the current year in the main dictionary
    year_key = f"year_{year}"
    all_data[year_key] = year_data

    # Merge rec_i dataframes using CASEID for the current year
    merged_data = None
    for file_key in year_data.keys():
        if merged_data is None:
            merged_data = year_data[file_key]['data']
        else:
            merged_data = merged_data.merge(year_data[file_key]['data'], on='CASEID')

    # Unify new_var_labels and new_value_labels into var_labels and value_labels for the current year
    var_labels = {}
    value_labels = {}

    for file_key in year_data.keys():
        var_labels.update(year_data[file_key]['var_labels'])
        value_labels.update(year_data[file_key]['value_labels'])

    # Generate new attributes for the merged data for the current year
    merged_data['var_labels'] = var_labels
    merged_data['value_labels'] = value_labels

    # Add the merged data for the current year to the main dictionary
    all_data[year_key]['merged_data'] = merged_data

In [15]:
import os
import pandas as pd

# Initialize the nested dictionary
all_data = {}

# Placeholder for variable labels and value labels
placeholder_var_labels = {}  # Replace this with your actual logic for variable labels
placeholder_value_labels = {}  # Replace this with your actual logic for value labels

# Specify the years
years = [2019, 2018, 2017, 2016, 2015]

# Specify the filenames
filenames = ["REC0111.sav", "RE223132.sav", "RE516171.sav"]

# Define the selected columns for each rec
selected_columns_rec = [
    ['CASEID', 'V000', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008', 'V009', 'V010', 'V011', 'V012', 'V024', 'V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127', 'V133'],
    ['CASEID', 'V201', 'V218', 'V301', 'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327', 'V337', 'V359', 'V360', 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A', 'V375A', 'V376', 'V376A', 'V379', 'V380'],
    ['CASEID', 'V501', 'V502', 'V503', 'V504', 'V505', 'V506', 'V507', 'V508', 'V509', 'V510', 'V511', 'V512', 'V513', 'V525', 'V613', 'V714', 'V715']
]

# Iterate through each year
for year in years:
    # Initialize a dictionary for the current year
    year_data = {}

    # Loop through each filename for the current year
    for filename in filenames:
        # Construct the file path
        file_path = f"../../_data/endes/{year}/{filename}"

        # Check if the file exists
        if os.path.exists(file_path):
            # Load data from the .sav file
            data = pd.read_spss(file_path)

            # Check for the existence of selected columns
            selected_columns = [col for col in selected_columns_rec[filenames.index(filename)] if col in data.columns]

            # Select the desired columns
            rec_i = data.loc[:, selected_columns]

            # Add a new column 'year' with the value of the current year
            rec_i['year'] = year

            # Update variable labels for rec_i (using a placeholder dictionary)
            new_var_labels_i = {key: f"New Var Label: {key}" for key in selected_columns}

            # Update value labels for rec_i (using a placeholder dictionary)
            new_value_labels_i = {key: f"New Value Label: {key}" for key in selected_columns}

            # Store data, var_labels, and value_labels in a nested dictionary
            file_key = f"{os.path.splitext(filename)[0]}_{year}"
            year_data[file_key] = {
                'data': rec_i,
                'var_labels': new_var_labels_i,
                'value_labels': new_value_labels_i
            }
        else:
            print(f"File not found: {file_path}")

    # Store the data for the current year in the main dictionary
    year_key = f"year_{year}"
    all_data[year_key] = year_data

    # Merge rec_i dataframes using CASEID for the current year
    merged_data = None
    for file_key in year_data.keys():
        if merged_data is None:
            merged_data = year_data[file_key]['data']
        else:
            merged_data = merged_data.merge(year_data[file_key]['data'], on='CASEID')

    # Unify new_var_labels and new_value_labels into var_labels and value_labels for the current year
    var_labels = {}
    value_labels = {}

    for file_key in year_data.keys():
        var_labels.update(year_data[file_key]['var_labels'])
        value_labels.update(year_data[file_key]['value_labels'])

    # Generate new attributes for the merged data for the current year
    merged_data['var_labels'] = var_labels
    merged_data['value_labels'] = value_labels

    # Add the merged data for the current year to the main dictionary
    all_data[year_key]['merged_data'] = merged_data

In [16]:
# After running the code, you can print the keys and structure of the all_data dictionary
for year_key, year_data in all_data.items():
    print(f"Year: {year_key}")
    
    for file_key, file_data in year_data.items():
        print(f"  File: {file_key}")
        
        # Check if the expected keys exist in the current file_data
        if 'data' in file_data and 'var_labels' in file_data and 'value_labels' in file_data:
            # Print data, variable labels, and value labels for each file
            print(f"    Data: {file_data['data'].head()}")  # Assuming you want to print the first few rows of data
            print(f"    Variable Labels: {file_data['var_labels']}")
            print(f"    Value Labels: {file_data['value_labels']}")
        else:
            print("    Missing data, var_labels, or value_labels key.")
    
    # Check if 'merged_data' key exists in the current year_data
    if 'merged_data' in year_data:
        # Print merged data for each year
        print(f"  Merged Data: {year_data['merged_data'].head()}")  # Assuming you want to print the first few rows of merged data
        print(f"  Variable Labels: {year_data['merged_data']['var_labels']}")
        print(f"  Value Labels: {year_data['merged_data']['value_labels']}")
    else:
        print("  No merged_data key found.")
    
    print("\n")

Year: year_2019
  File: REC0111_2019
    Data:                CASEID V000  V001  V002  V003  V004    V007    V008  V009  \
0        000100201  2  PE6   1.0   2.0   2.0   1.0  2019.0  1434.0   4.0
1        000100201  3  PE6   1.0   2.0   3.0   1.0  2019.0  1434.0   1.0
2        000102801  2  PE6   1.0  28.0   2.0   1.0  2019.0  1434.0   6.0
3        000102801  6  PE6   1.0  28.0   6.0   1.0  2019.0  1434.0   3.0
4        000104801  2  PE6   1.0  48.0   2.0   1.0  2019.0  1434.0   5.0

     V010  ...    V102  V120 V121 V122 V123 V124 V125  \
0  1986.0  ...  Urbano    Si   Si   Si   No   No   No
1  2007.0  ...  Urbano    Si   Si   Si   No   No   No
2  1983.0  ...  Urbano    Si   Si   Si   Si   Si   Si
3  1970.0  ...  Urbano    Si   Si   Si   Si   Si   Si
4  1991.0  ...  Urbano    No   No   No   No   No   No

                            V127  V133  year
0  Losetas, terrazos o similares  16.0  2019
1  Losetas, terrazos o similares   6.0  2019
2  Losetas, terrazos o similares  16.0  2019
3  Losetas, terrazos o similares   4.0  2019
4               Cemento/ladrillo   1.0  2019

[5 rows x 23 columns]
    Variable Labels: {'CASEID': 'New Var Label: CASEID', 'V000': 'New Var Label: V000', 'V001': 'New Var Label: V001', 'V002': 'New Var Label: V002', 'V003': 'New Var Label: V003', 'V004': 'New Var Label: V004', 'V007': 'New Var Label: V007', 'V008': 'New Var Label: V008', 'V009': 'New Var Label: V009', 'V010': 'New Var Label: V010', 'V011': 'New Var Label: V011', 'V012': 'New Var Label: V012', 'V024': 'New Var Label: V024', 'V102': 'New Var Label: V102', 'V120': 'New Var Label: V120', 'V121': 'New Var Label: V121', 'V122': 'New Var Label: V122', 'V123': 'New Var Label: V123', 'V124': 'New Var Label: V124', 'V125': 'New Var Label: V125', 'V127': 'New Var Label: V127', 'V133': 'New Var Label: V133'}
    Value Labels: {'CASEID': 'New Value Label: CASEID', 'V000': 'New Value Label: V000', 'V001': 'New Value Label: V001', 'V002': 'New Value Label: V002', 'V003': 'New Value Label: V003', 'V004': 'New Value Label: V004', 'V007': 'New Value Label: V007', 'V008': 'New Value Label: V008', 'V009': 'New Value Label: V009', 'V010': 'New Value Label: V010', 'V011': 'New Value Label: V011', 'V012': 'New Value Label: V012', 'V024': 'New Value Label: V024', 'V102': 'New Value Label: V102', 'V120': 'New Value Label: V120', 'V121': 'New Value Label: V121', 'V122': 'New Value Label: V122', 'V123': 'New Value Label: V123', 'V124': 'New Value Label: V124', 'V125': 'New Value Label: V125', 'V127': 'New Value Label: V127', 'V133': 'New Value Label: V133'}
  File: RE223132_2019
    Data:                CASEID  V201  V218                     V301  \
0        000100201  2   2.0   2.0  No conoce ningún método
1        000100201  3   0.0   0.0                      NaN
2        000102801  2   3.0   3.0  No conoce ningún método
3        000102801  6   3.0   3.0  No conoce ningún método
4        000104801  2   3.0   3.0  No conoce ningún método

                    V302 V323 V323A V325A                   V326  \
0       Metodos modernos  NaN   NaN   NaN        Farmacia/botica
1                    NaN  NaN   NaN   NaN                    NaN
2       Metodos modernos  NaN   NaN   NaN       Hospital ESSALUD
3  Metodos tradicionales  NaN   NaN   NaN                    NaN
4       Metodos modernos  NaN   NaN   NaN  Puesto de salud MINSA

                                                V327  ...  \
0                                    Farmacia/botica  ...
1                                                NaN  ...
2  Hospital, Centro de Salud, Puesto de Salud, Po...  ...
3                                                NaN  ...
4  Hospital, Centro de Salud, Puesto de Salud, Po...  ...

                       V364         V367 V372 V372A       V375A  \
0  Usando el método moderno     Entonces  NaN   NaN         NaN
1                       NaN          NaN  NaN   NaN         NaN
2  Usando el método moderno  Esperar más  NaN   NaN         NaN
3  No tiene la intención de          NaN  NaN   NaN  Menopausia
4  Usando el método moderno  Esperar más  NaN   NaN         NaN

                 V376 V376A V379 V380  year
0                 NaN   NaN  NaN  NaN  2019
1                 NaN   NaN  NaN  NaN  2019
2                 NaN   NaN  NaN  NaN  2019
3  Infertilidad mujer   NaN  NaN  NaN  2019
4                 NaN   NaN  NaN  NaN  2019

[5 rows x 26 columns]
    Variable Labels: {'CASEID': 'New Var Label: CASEID', 'V201': 'New Var Label: V201', 'V218': 'New Var Label: V218', 'V301': 'New Var Label: V301', 'V302': 'New Var Label: V302', 'V323': 'New Var Label: V323', 'V323A': 'New Var Label: V323A', 'V325A': 'New Var Label: V325A', 'V326': 'New Var Label: V326', 'V327': 'New Var Label: V327', 'V337': 'New Var Label: V337', 'V359': 'New Var Label: V359', 'V360': 'New Var Label: V360', 'V361': 'New Var Label: V361', 'V362': 'New Var Label: V362', 'V363': 'New Var Label: V363', 'V364': 'New Var Label: V364', 'V367': 'New Var Label: V367', 'V372': 'New Var Label: V372', 'V372A': 'New Var Label: V372A', 'V375A': 'New Var Label: V375A', 'V376': 'New Var Label: V376', 'V376A': 'New Var Label: V376A', 'V379': 'New Var Label: V379', 'V380': 'New Var Label: V380'}
    Value Labels: {'CASEID': 'New Value Label: CASEID', 'V201': 'New Value Label: V201', 'V218': 'New Value Label: V218', 'V301': 'New Value Label: V301', 'V302': 'New Value Label: V302', 'V323': 'New Value Label: V323', 'V323A': 'New Value Label: V323A', 'V325A': 'New Value Label: V325A', 'V326': 'New Value Label: V326', 'V327': 'New Value Label: V327', 'V337': 'New Value Label: V337', 'V359': 'New Value Label: V359', 'V360': 'New Value Label: V360', 'V361': 'New Value Label: V361', 'V362': 'New Value Label: V362', 'V363': 'New Value Label: V363', 'V364': 'New Value Label: V364', 'V367': 'New Value Label: V367', 'V372': 'New Value Label: V372', 'V372A': 'New Value Label: V372A', 'V375A': 'New Value Label: V375A', 'V376': 'New Value Label: V376', 'V376A': 'New Value Label: V376A', 'V379': 'New Value Label: V379', 'V380': 'New Value Label: V380'}
  File: RE516171_2019
    Data:                CASEID             V501                  V502            V503  \
0        000100201  2           Casado    Actualmente casada         Una vez
1        000102801  2  Viviendo juntos    Actualmente casada         Una vez
2        000102801  6  No viven juntos  Anteriormente casada         Una vez
3        000104801  2  Viviendo juntos    Actualmente casada         Una vez
4        000113601  2  Viviendo juntos    Actualmente casada  Mas de una vez

            V504 V505 V506  V507    V508    V509                    V510  \
0  Vive con ella  NaN  NaN   1.0  2008.0  1297.0         Tiene mes y año
1  Vive con ella  NaN  NaN  12.0  2011.0  1344.0         Tiene mes y año
2            NaN  NaN  NaN   8.0  1984.0  1016.0  Tiene año - imputa mes
3  Vive con ella  NaN  NaN  12.0  2009.0  1320.0         Tiene mes y año
4  Vive con ella  NaN  NaN  12.0  2005.0  1272.0         Tiene mes y año

   V511  V512              V513  V525 V613 V714  V715  year
0  21.0  11.0   De 10 a 14 años  17.0  2.0   Sí  11.0  2019
1  28.0   7.0     De 5 a 9 años  18.0  3.0   Sí  14.0  2019
2  14.0  34.0  De 30 a más años  14.0  0.0   No   6.0  2019
3  18.0   9.0     De 5 a 9 años  15.0  2.0   No   6.0  2019
4  17.0  13.0   De 10 a 14 años  15.0  2.0   Sí  16.0  2019
    Variable Labels: {'CASEID': 'New Var Label: CASEID', 'V501': 'New Var Label: V501', 'V502': 'New Var Label: V502', 'V503': 'New Var Label: V503', 'V504': 'New Var Label: V504', 'V505': 'New Var Label: V505', 'V506': 'New Var Label: V506', 'V507': 'New Var Label: V507', 'V508': 'New Var Label: V508', 'V509': 'New Var Label: V509', 'V510': 'New Var Label: V510', 'V511': 'New Var Label: V511', 'V512': 'New Var Label: V512', 'V513': 'New Var Label: V513', 'V525': 'New Var Label: V525', 'V613': 'New Var Label: V613', 'V714': 'New Var Label: V714', 'V715': 'New Var Label: V715'}
    Value Labels: {'CASEID': 'New Value Label: CASEID', 'V501': 'New Value Label: V501', 'V502': 'New Value Label: V502', 'V503': 'New Value Label: V503', 'V504': 'New Value Label: V504', 'V505': 'New Value Label: V505', 'V506': 'New Value Label: V506', 'V507': 'New Value Label: V507', 'V508': 'New Value Label: V508', 'V509': 'New Value Label: V509', 'V510': 'New Value Label: V510', 'V511': 'New Value Label: V511', 'V512': 'New Value Label: V512', 'V513': 'New Value Label: V513', 'V525': 'New Value Label: V525', 'V613': 'New Value Label: V613', 'V714': 'New Value Label: V714', 'V715': 'New Value Label: V715'}
  File: merged_data
    Missing data, var_labels, or value_labels key.
  Merged Data:                CASEID V000  V001   V002  V003  V004    V007    V008  V009  \
0        000100201  2  PE6   1.0    2.0   2.0   1.0  2019.0  1434.0   4.0
1        000102801  2  PE6   1.0   28.0   2.0   1.0  2019.0  1434.0   6.0
2        000102801  6  PE6   1.0   28.0   6.0   1.0  2019.0  1434.0   3.0
3        000104801  2  PE6   1.0   48.0   2.0   1.0  2019.0  1434.0   5.0
4        000113601  2  PE6   1.0  136.0   2.0   1.0  2019.0  1434.0  11.0

     V010  ...  V511  V512              V513  V525 V613 V714  V715  year  \
0  1986.0  ...  21.0  11.0   De 10 a 14 años  17.0  2.0   Sí  11.0  2019
1  1983.0  ...  28.0   7.0     De 5 a 9 años  18.0  3.0   Sí  14.0  2019
2  1970.0  ...  14.0  34.0  De 30 a más años  14.0  0.0   No   6.0  2019
3  1991.0  ...  18.0   9.0     De 5 a 9 años  15.0  2.0   No   6.0  2019
4  1988.0  ...  17.0  13.0   De 10 a 14 años  15.0  2.0   Sí  16.0  2019

  var_labels value_labels
0        NaN          NaN
1        NaN          NaN
2        NaN          NaN
3        NaN          NaN
4        NaN          NaN

[5 rows x 68 columns]
  Variable Labels: 0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
33306    NaN
33307    NaN
33308    NaN
33309    NaN
33310    NaN
Name: var_labels, Length: 33311, dtype: object
  Value Labels: 0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
33306    NaN
33307    NaN
33308    NaN
33309    NaN
33310    NaN
Name: value_labels, Length: 33311, dtype: object


Year: year_2018
  File: REC0111_2018
    Data:                CASEID V000  V001  V002  V003  V004    V008  V009    V010  \
0        000100701  2  PE6   1.0   7.0   2.0   1.0  1422.0   8.0  1975.0
1        000100701  3  PE6   1.0   7.0   3.0   1.0  1422.0   2.0  2002.0
2        000101401  2  PE6   1.0  14.0   2.0   1.0  1422.0   6.0  1997.0
3        000103501  4  PE6   1.0  35.0   4.0   1.0  1422.0   6.0  2001.0
4        000103501  5  PE6   1.0  35.0   5.0   1.0  1422.0   5.0  2006.0

     V011  ...    V102 V120 V121 V122 V123 V124 V125              V127  V133  \
0   909.0  ...  Urbana   Si   Si   No   No   No   No  Cemento o bloque   4.0
1  1227.0  ...  Urbana   Si   Si   No   No   No   No  Cemento o bloque  10.0
2  1171.0  ...  Urbana   No   No   No   No   No   No  Cemento o bloque  12.0
3  1219.0  ...  Urbana   Si   Si   Si   No   Si   No  Cemento o bloque  11.0
4  1278.0  ...  Urbana   Si   Si   Si   No   Si   No  Cemento o bloque   6.0

   year
0  2018
1  2018
2  2018
3  2018
4  2018

[5 rows x 22 columns]
    Variable Labels: {'CASEID': 'New Var Label: CASEID', 'V000': 'New Var Label: V000', 'V001': 'New Var Label: V001', 'V002': 'New Var Label: V002', 'V003': 'New Var Label: V003', 'V004': 'New Var Label: V004', 'V008': 'New Var Label: V008', 'V009': 'New Var Label: V009', 'V010': 'New Var Label: V010', 'V011': 'New Var Label: V011', 'V012': 'New Var Label: V012', 'V024': 'New Var Label: V024', 'V102': 'New Var Label: V102', 'V120': 'New Var Label: V120', 'V121': 'New Var Label: V121', 'V122': 'New Var Label: V122', 'V123': 'New Var Label: V123', 'V124': 'New Var Label: V124', 'V125': 'New Var Label: V125', 'V127': 'New Var Label: V127', 'V133': 'New Var Label: V133'}
    Value Labels: {'CASEID': 'New Value Label: CASEID', 'V000': 'New Value Label: V000', 'V001': 'New Value Label: V001', 'V002': 'New Value Label: V002', 'V003': 'New Value Label: V003', 'V004': 'New Value Label: V004', 'V008': 'New Value Label: V008', 'V009': 'New Value Label: V009', 'V010': 'New Value Label: V010', 'V011': 'New Value Label: V011', 'V012': 'New Value Label: V012', 'V024': 'New Value Label: V024', 'V102': 'New Value Label: V102', 'V120': 'New Value Label: V120', 'V121': 'New Value Label: V121', 'V122': 'New Value Label: V122', 'V123': 'New Value Label: V123', 'V124': 'New Value Label: V124', 'V125': 'New Value Label: V125', 'V127': 'New Value Label: V127', 'V133': 'New Value Label: V133'}
  File: RE223132_2018
    Data:                CASEID  V201  V218              V301                V302 V323  \
0        000100701  2   7.0   7.0  No conoce método  Uso método moderno  NaN
1        000100701  3   0.0   0.0  No conoce método           Nunca uso  NaN
2        000101401  2   1.0   1.0  No conoce método  Uso método moderno  NaN
3        000103501  4   0.0   0.0  No conoce método  Uso método moderno  NaN
4        000103501  5   0.0   0.0               NaN                 NaN  NaN

  V323A V325A V326 V327  ...                       V364            V367 V372  \
0   NaN   NaN  NaN  NaN  ...  Usando método tradicional  Nunca lo quiso  NaN
1   NaN   NaN  NaN  NaN  ...     No usa intenta hacerlo             NaN  NaN
2   NaN   NaN  NaN  NaN  ...  Usando método tradicional  Lo quiso luego  NaN
3   NaN   NaN  NaN  NaN  ...  Usando método tradicional             NaN  NaN
4   NaN   NaN  NaN  NaN  ...                        NaN             NaN  NaN

  V372A                         V375A V376 V376A V379 V380  year
0   NaN                           NaN  NaN   NaN  NaN  NaN  2018
1   NaN  No tiene relaciones sexuales  NaN   NaN  NaN  NaN  2018
2   NaN                           NaN  NaN   NaN  NaN  NaN  2018
3   NaN                           NaN  NaN   NaN  NaN  NaN  2018
4   NaN                           NaN  NaN   NaN  NaN  NaN  2018

[5 rows x 26 columns]
    Variable Labels: {'CASEID': 'New Var Label: CASEID', 'V201': 'New Var Label: V201', 'V218': 'New Var Label: V218', 'V301': 'New Var Label: V301', 'V302': 'New Var Label: V302', 'V323': 'New Var Label: V323', 'V323A': 'New Var Label: V323A', 'V325A': 'New Var Label: V325A', 'V326': 'New Var Label: V326', 'V327': 'New Var Label: V327', 'V337': 'New Var Label: V337', 'V359': 'New Var Label: V359', 'V360': 'New Var Label: V360', 'V361': 'New Var Label: V361', 'V362': 'New Var Label: V362', 'V363': 'New Var Label: V363', 'V364': 'New Var Label: V364', 'V367': 'New Var Label: V367', 'V372': 'New Var Label: V372', 'V372A': 'New Var Label: V372A', 'V375A': 'New Var Label: V375A', 'V376': 'New Var Label: V376', 'V376A': 'New Var Label: V376A', 'V379': 'New Var Label: V379', 'V380': 'New Var Label: V380'}
    Value Labels: {'CASEID': 'New Value Label: CASEID', 'V201': 'New Value Label: V201', 'V218': 'New Value Label: V218', 'V301': 'New Value Label: V301', 'V302': 'New Value Label: V302', 'V323': 'New Value Label: V323', 'V323A': 'New Value Label: V323A', 'V325A': 'New Value Label: V325A', 'V326': 'New Value Label: V326', 'V327': 'New Value Label: V327', 'V337': 'New Value Label: V337', 'V359': 'New Value Label: V359', 'V360': 'New Value Label: V360', 'V361': 'New Value Label: V361', 'V362': 'New Value Label: V362', 'V363': 'New Value Label: V363', 'V364': 'New Value Label: V364', 'V367': 'New Value Label: V367', 'V372': 'New Value Label: V372', 'V372A': 'New Value Label: V372A', 'V375A': 'New Value Label: V375A', 'V376': 'New Value Label: V376', 'V376A': 'New Value Label: V376A', 'V379': 'New Value Label: V379', 'V380': 'New Value Label: V380'}
  File: RE516171_2018
    Data:                CASEID           V501                V502     V503  \
0        000100701  2         Casada  Actualmente casada  Una vez
1        000100701  3  Nunca se caso        Nunca casada      NaN
2        000101401  2    Conviviente  Actualmente casada  Una vez
3        000103501  4  Nunca se caso        Nunca casada      NaN
4        000105301  2    Conviviente  Actualmente casada  Una vez

                V504 V505 V506  V507    V508    V509                  V510  \
0      Vive con ella  NaN  NaN   1.0  1995.0  1141.0  Edad - a, m imputado
1                NaN  NaN  NaN   NaN     NaN     NaN                   NaN
2      Vive con ella  NaN  NaN   7.0  2016.0  1399.0             Mes y año
3                NaN  NaN  NaN   NaN     NaN     NaN                   NaN
4  Vive en otro lado  NaN  NaN   3.0  2015.0  1383.0             Mes y año

   V511  V512          V513                          V525 V613 V714  V715  \
0  19.0  23.0         20-24                          18.0  2.0   Si   6.0
1   NaN   NaN  Nunca casada  No ha tenido relación sexual  2.0   No   NaN
2  19.0   1.0           0-4                          17.0  2.0   No  11.0
3   NaN   NaN  Nunca casada                          16.0  2.0   No   NaN
4  22.0   3.0           0-4                          20.0  2.0   No  16.0

   year
0  2018
1  2018
2  2018
3  2018
4  2018
    Variable Labels: {'CASEID': 'New Var Label: CASEID', 'V501': 'New Var Label: V501', 'V502': 'New Var Label: V502', 'V503': 'New Var Label: V503', 'V504': 'New Var Label: V504', 'V505': 'New Var Label: V505', 'V506': 'New Var Label: V506', 'V507': 'New Var Label: V507', 'V508': 'New Var Label: V508', 'V509': 'New Var Label: V509', 'V510': 'New Var Label: V510', 'V511': 'New Var Label: V511', 'V512': 'New Var Label: V512', 'V513': 'New Var Label: V513', 'V525': 'New Var Label: V525', 'V613': 'New Var Label: V613', 'V714': 'New Var Label: V714', 'V715': 'New Var Label: V715'}
    Value Labels: {'CASEID': 'New Value Label: CASEID', 'V501': 'New Value Label: V501', 'V502': 'New Value Label: V502', 'V503': 'New Value Label: V503', 'V504': 'New Value Label: V504', 'V505': 'New Value Label: V505', 'V506': 'New Value Label: V506', 'V507': 'New Value Label: V507', 'V508': 'New Value Label: V508', 'V509': 'New Value Label: V509', 'V510': 'New Value Label: V510', 'V511': 'New Value Label: V511', 'V512': 'New Value Label: V512', 'V513': 'New Value Label: V513', 'V525': 'New Value Label: V525', 'V613': 'New Value Label: V613', 'V714': 'New Value Label: V714', 'V715': 'New Value Label: V715'}
  File: merged_data
    Missing data, var_labels, or value_labels key.
  Merged Data:                CASEID V000  V001  V002  V003  V004    V008  V009    V010  \
0        000100701  2  PE6   1.0   7.0   2.0   1.0  1422.0   8.0  1975.0
1        000100701  3  PE6   1.0   7.0   3.0   1.0  1422.0   2.0  2002.0
2        000101401  2  PE6   1.0  14.0   2.0   1.0  1422.0   6.0  1997.0
3        000103501  4  PE6   1.0  35.0   4.0   1.0  1422.0   6.0  2001.0
4        000105301  2  PE6   1.0  53.0   2.0   1.0  1422.0  12.0  1992.0

     V011  ...  V511  V512          V513                          V525 V613  \
0   909.0  ...  19.0  23.0         20-24                          18.0  2.0
1  1227.0  ...   NaN   NaN  Nunca casada  No ha tenido relación sexual  2.0
2  1171.0  ...  19.0   1.0           0-4                          17.0  2.0
3  1219.0  ...   NaN   NaN  Nunca casada                          16.0  2.0
4  1117.0  ...  22.0   3.0           0-4                          20.0  2.0

  V714  V715  year var_labels value_labels
0   Si   6.0  2018        NaN          NaN
1   No   NaN  2018        NaN          NaN
2   No  11.0  2018        NaN          NaN
3   No   NaN  2018        NaN          NaN
4   No  16.0  2018        NaN          NaN

[5 rows x 67 columns]
  Variable Labels: 0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
34991    NaN
34992    NaN
34993    NaN
34994    NaN
34995    NaN
Name: var_labels, Length: 34996, dtype: object
  Value Labels: 0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
34991    NaN
34992    NaN
34993    NaN
34994    NaN
34995    NaN
Name: value_labels, Length: 34996, dtype: object


Year: year_2017
  File: REC0111_2017
    Data:                CASEID V000  V001  V002  V003  V004    V007    V008 V009  \

    Data:                CASEID             V501               V502            V503  \
0        000102501  2  Living together  Currently married  More than once
1        000103201  2  Living together  Currently married            Once
2        000103601  2  Living together  Currently married            Once
3        000104501  2  Living together  Currently married  More than once
4        000105201  2  Living together  Currently married            Once

              V504 V505 V506  V507    V508    V509             V510  V511  \
0  Living with her  NaN  NaN   8.0  1994.0  1136.0  Year - a, m imp  16.0
1  Living with her  NaN  NaN  12.0  2011.0  1344.0   Month and year  16.0
2  Living with her  NaN  NaN  12.0  2013.0  1368.0   Month and year  15.0
3  Living with her  NaN  NaN  11.0  2000.0  1211.0   Month and year  16.0
4  Living with her  NaN  NaN   6.0  2015.0  1386.0   Month and year  31.0

   V512   V513  V525                  V613 V714        V715  year
0  22.0  20-24  16.0                   2.0  Yes         6.0  2017
1   5.0    5-9  16.0                   2.0   No        11.0  2017
2   3.0    0-4  15.0                   0.0  Yes        11.0  2017
3  16.0  15-19  14.0  Non-numeric response   No         6.0  2017
4   1.0    0-4  17.0                   2.0   No  Don't know  2017
    Variable Labels: {'CASEID': 'New Var Label: CASEID', 'V501': 'New Var Label: V501', 'V502': 'New Var Label: V502', 'V503': 'New Var Label: V503', 'V504': 'New Var Label: V504', 'V505': 'New Var Label: V505', 'V506': 'New Var Label: V506', 'V507': 'New Var Label: V507', 'V508': 'New Var Label: V508', 'V509': 'New Var Label: V509', 'V510': 'New Var Label: V510', 'V511': 'New Var Label: V511', 'V512': 'New Var Label: V512', 'V513': 'New Var Label: V513', 'V525': 'New Var Label: V525', 'V613': 'New Var Label: V613', 'V714': 'New Var Label: V714', 'V715': 'New Var Label: V715'}
    Value Labels: {'CASEID': 'New Value Label: CASEID', 'V501': 'New Value Label: V501', 'V502': 'New Value Label: V502', 'V503': 'New Value Label: V503', 'V504': 'New Value Label: V504', 'V505': 'New Value Label: V505', 'V506': 'New Value Label: V506', 'V507': 'New Value Label: V507', 'V508': 'New Value Label: V508', 'V509': 'New Value Label: V509', 'V510': 'New Value Label: V510', 'V511': 'New Value Label: V511', 'V512': 'New Value Label: V512', 'V513': 'New Value Label: V513', 'V525': 'New Value Label: V525', 'V613': 'New Value Label: V613', 'V714': 'New Value Label: V714', 'V715': 'New Value Label: V715'}
  File: merged_data
    Missing data, var_labels, or value_labels key.
  Merged Data:                CASEID V000  V001  V002  V003  V004    V007    V008 V009  \
0        000102501  2  PE6   1.0  25.0   2.0   1.0  2017.0  1409.0  3.0
1        000103201  2  PE6   1.0  32.0   2.0   1.0  2017.0  1409.0  2.0
2        000103601  2  PE6   1.0  36.0   2.0   1.0  2017.0  1409.0  5.0
3        000104501  2  PE6   1.0  45.0   2.0   1.0  2017.0  1409.0  4.0
4        000105201  2  PE6   1.0  52.0   2.0   1.0  2017.0  1409.0  4.0

     V010  ...  V511  V512   V513  V525                  V613 V714  \
0  1978.0  ...  16.0  22.0  20-24  16.0                   2.0  Yes
1  1995.0  ...  16.0   5.0    5-9  16.0                   2.0   No
2  1998.0  ...  15.0   3.0    0-4  15.0                   0.0  Yes
3  1984.0  ...  16.0  16.0  15-19  14.0  Non-numeric response   No
4  1984.0  ...  31.0   1.0    0-4  17.0                   2.0   No

         V715  year var_labels value_labels
0         6.0  2017        NaN          NaN
1        11.0  2017        NaN          NaN
2        11.0  2017        NaN          NaN
3         6.0  2017        NaN          NaN
4  Don't know  2017        NaN          NaN

[5 rows x 68 columns]
  Variable Labels: 0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
33163    NaN
33164    NaN
33165    NaN
33166    NaN
33167    NaN
Name: var_labels, Length: 33168, dtype: object
  Value Labels: 0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
33163    NaN
33164    NaN
33165    NaN
33166    NaN
33167    NaN
Name: value_labels, Length: 33168, dtype: object


Year: year_2016
  File: REC0111_2016
    Data:                CASEID V000  V001  V002  V003  V004    V007    V008  V009  \
0        000100301  2  PE6   1.0   3.0   2.0   1.0  2016.0  1398.0  11.0
1        000102801  1  PE6   1.0  28.0   1.0   1.0  2016.0  1398.0  10.0
2        000102801  2  PE6   1.0  28.0   2.0   1.0  2016.0  1398.0   6.0
3        000106101  2  PE6   1.0  61.0   2.0   1.0  2016.0  1398.0   4.0
4        000106801  2  PE6   1.0  68.0   2.0   1.0  2016.0  1398.0   6.0

     V010  ...   V102  V120 V121 V122 V123 V124 V125                 V127  \
0  1982.0  ...  Urban   Yes  Yes  Yes   No  Yes   No  Asphlat tiles/vynil
1  1979.0  ...  Urban   Yes  Yes   No   No   No   No         Cement/brick
2  1998.0  ...  Urban   Yes  Yes   No   No   No   No         Cement/brick
3  1990.0  ...  Urban   Yes  Yes   No   No   No   No           Earth/sand
4  1973.0  ...  Urban   Yes  Yes   No   No   No   No           Earth/sand

   V133  year
0  11.0  2016
1   3.0  2016
2  12.0  2016
3  14.0  2016
4  11.0  2016

[5 rows x 23 columns]
    Variable Labels: {'CASEID': 'New Var Label: CASEID', 'V000': 'New Var Label: V000', 'V001': 'New Var Label: V001', 'V002': 'New Var Label: V002', 'V003': 'New Var Label: V003', 'V004': 'New Var Label: V004', 'V007': 'New Var Label: V007', 'V008': 'New Var Label: V008', 'V009': 'New Var Label: V009', 'V010': 'New Var Label: V010', 'V011': 'New Var Label: V011', 'V012': 'New Var Label: V012', 'V024': 'New Var Label: V024', 'V102': 'New Var Label: V102', 'V120': 'New Var Label: V120', 'V121': 'New Var Label: V121', 'V122': 'New Var Label: V122', 'V123': 'New Var Label: V123', 'V124': 'New Var Label: V124', 'V125': 'New Var Label: V125', 'V127': 'New Var Label: V127', 'V133': 'New Var Label: V133'}
    Value Labels: {'CASEID': 'New Value Label: CASEID', 'V000': 'New Value Label: V000', 'V001': 'New Value Label: V001', 'V002': 'New Value Label: V002', 'V003': 'New Value Label: V003', 'V004': 'New Value Label: V004', 'V007': 'New Value Label: V007', 'V008': 'New Value Label: V008', 'V009': 'New Value Label: V009', 'V010': 'New Value Label: V010', 'V011': 'New Value Label: V011', 'V012': 'New Value Label: V012', 'V024': 'New Value Label: V024', 'V102': 'New Value Label: V102', 'V120': 'New Value Label: V120', 'V121': 'New Value Label: V121', 'V122': 'New Value Label: V122', 'V123': 'New Value Label: V123', 'V124': 'New Value Label: V124', 'V125': 'New Value Label: V125', 'V127': 'New Value Label: V127', 'V133': 'New Value Label: V133'}
  File: RE223132_2016
    Data:                CASEID  V201  V218             V301                  V302 V323  \
0        000100301  2   1.0   1.0  Knows no method    Used modern method  NaN
1        000102801  1   3.0   3.0  Knows no method    Used modern method  NaN
2        000102801  2   0.0   0.0  Knows no method    Used modern method  NaN
3        000106101  2   1.0   1.0  Knows no method  Used only trad. meth  NaN
4        000106801  2   2.0   2.0  Knows no method    Used modern method  NaN

  V323A V325A                 V326                 V327  ...  \
0   NaN   NaN                  NaN                  NaN  ...
1   NaN   NaN  Health center MINSA  Govt Clinical/Pharm  ...
2   NaN   NaN             Pharmacy     Private Pharmacy  ...
3   NaN   NaN                  NaN                  NaN  ...
4   NaN   NaN  Health center MINSA  Govt Clinical/Pharm  ...

                       V364          V367 V372 V372A     V375A V376 V376A  \
0        Non-user intend to  Wanted later  NaN   NaN  Pregnant  NaN   NaN
1       Using modern method  Wanted later  NaN   NaN       NaN  NaN   NaN
2       Using modern method           NaN  NaN   NaN       NaN  NaN   NaN
3  Using traditional method  Wanted later  NaN   NaN       NaN  NaN   NaN
4       Using modern method           NaN  NaN   NaN       NaN  NaN   NaN

  V379 V380  year
0  NaN  NaN  2016
1  NaN  NaN  2016
2  NaN  NaN  2016
3  NaN  NaN  2016
4  NaN  NaN  2016

[5 rows x 26 columns]
    Variable Labels: {'CASEID': 'New Var Label: CASEID', 'V201': 'New Var Label: V201', 'V218': 'New Var Label: V218', 'V301': 'New Var Label: V301', 'V302': 'New Var Label: V302', 'V323': 'New Var Label: V323', 'V323A': 'New Var Label: V323A', 'V325A': 'New Var Label: V325A', 'V326': 'New Var Label: V326', 'V327': 'New Var Label: V327', 'V337': 'New Var Label: V337', 'V359': 'New Var Label: V359', 'V360': 'New Var Label: V360', 'V361': 'New Var Label: V361', 'V362': 'New Var Label: V362', 'V363': 'New Var Label: V363', 'V364': 'New Var Label: V364', 'V367': 'New Var Label: V367', 'V372': 'New Var Label: V372', 'V372A': 'New Var Label: V372A', 'V375A': 'New Var Label: V375A', 'V376': 'New Var Label: V376', 'V376A': 'New Var Label: V376A', 'V379': 'New Var Label: V379', 'V380': 'New Var Label: V380'}
    Value Labels: {'CASEID': 'New Value Label: CASEID', 'V201': 'New Value Label: V201', 'V218': 'New Value Label: V218', 'V301': 'New Value Label: V301', 'V302': 'New Value Label: V302', 'V323': 'New Value Label: V323', 'V323A': 'New Value Label: V323A', 'V325A': 'New Value Label: V325A', 'V326': 'New Value Label: V326', 'V327': 'New Value Label: V327', 'V337': 'New Value Label: V337', 'V359': 'New Value Label: V359', 'V360': 'New Value Label: V360', 'V361': 'New Value Label: V361', 'V362': 'New Value Label: V362', 'V363': 'New Value Label: V363', 'V364': 'New Value Label: V364', 'V367': 'New Value Label: V367', 'V372': 'New Value Label: V372', 'V372A': 'New Value Label: V372A', 'V375A': 'New Value Label: V375A', 'V376': 'New Value Label: V376', 'V376A': 'New Value Label: V376A', 'V379': 'New Value Label: V379', 'V380': 'New Value Label: V380'}
  File: RE516171_2016
    Data:                CASEID             V501               V502            V503  \
0        000100301  2  Living together  Currently married            Once
1        000102801  1          Married  Currently married            Once
2        000102801  2    Never married      Never married             NaN
3        000106101  2  Living together  Currently married            Once
4        000106801  2          Married  Currently married  More than once

                V504 V505 V506  V507    V508    V509             V510  V511  \
0    Living with her  NaN  NaN   8.0  2012.0  1352.0   Month and year  29.0
1  Staying elsewhere  NaN  NaN   7.0  1993.0  1123.0  Year - a, m imp  13.0
2                NaN  NaN  NaN   NaN     NaN     NaN              NaN   NaN
3    Living with her  NaN  NaN  10.0  2013.0  1366.0   Month and year  23.0
4    Living with her  NaN  NaN   1.0  1992.0  1105.0   Month and year  18.0

   V512           V513  V525 V613 V714  V715  year
0   3.0            0-4  19.0  2.0   No   9.0  2016
1  22.0          20-24  13.0  5.0  Yes   6.0  2016
2   NaN  Never married  16.0  1.0  Yes   NaN  2016
3   2.0            0-4  20.0  4.0   No  16.0  2016
4  24.0          20-24  18.0  2.0  Yes   8.0  2016
    Variable Labels: {'CASEID': 'New Var Label: CASEID', 'V501': 'New Var Label: V501', 'V502': 'New Var Label: V502', 'V503': 'New Var Label: V503', 'V504': 'New Var Label: V504', 'V505': 'New Var Label: V505', 'V506': 'New Var Label: V506', 'V507': 'New Var Label: V507', 'V508': 'New Var Label: V508', 'V509': 'New Var Label: V509', 'V510': 'New Var Label: V510', 'V511': 'New Var Label: V511', 'V512': 'New Var Label: V512', 'V513': 'New Var Label: V513', 'V525': 'New Var Label: V525', 'V613': 'New Var Label: V613', 'V714': 'New Var Label: V714', 'V715': 'New Var Label: V715'}
    Value Labels: {'CASEID': 'New Value Label: CASEID', 'V501': 'New Value Label: V501', 'V502': 'New Value Label: V502', 'V503': 'New Value Label: V503', 'V504': 'New Value Label: V504', 'V505': 'New Value Label: V505', 'V506': 'New Value Label: V506', 'V507': 'New Value Label: V507', 'V508': 'New Value Label: V508', 'V509': 'New Value Label: V509', 'V510': 'New Value Label: V510', 'V511': 'New Value Label: V511', 'V512': 'New Value Label: V512', 'V513': 'New Value Label: V513', 'V525': 'New Value Label: V525', 'V613': 'New Value Label: V613', 'V714': 'New Value Label: V714', 'V715': 'New Value Label: V715'}
  File: merged_data
    Missing data, var_labels, or value_labels key.
  Merged Data:                CASEID V000  V001  V002  V003  V004    V007    V008  V009  \
0        000100301  2  PE6   1.0   3.0   2.0   1.0  2016.0  1398.0  11.0
1        000102801  1  PE6   1.0  28.0   1.0   1.0  2016.0  1398.0  10.0
2        000102801  2  PE6   1.0  28.0   2.0   1.0  2016.0  1398.0   6.0
3        000106101  2  PE6   1.0  61.0   2.0   1.0  2016.0  1398.0   4.0
4        000106801  2  PE6   1.0  68.0   2.0   1.0  2016.0  1398.0   6.0

     V010  ...  V511  V512           V513  V525 V613 V714  V715  year  \
0  1982.0  ...  29.0   3.0            0-4  19.0  2.0   No   9.0  2016
1  1979.0  ...  13.0  22.0          20-24  13.0  5.0  Yes   6.0  2016
2  1998.0  ...   NaN   NaN  Never married  16.0  1.0  Yes   NaN  2016
3  1990.0  ...  23.0   2.0            0-4  20.0  4.0   No  16.0  2016
4  1973.0  ...  18.0  24.0          20-24  18.0  2.0  Yes   8.0  2016

  var_labels value_labels
0        NaN          NaN
1        NaN          NaN
2        NaN          NaN
3        NaN          NaN
4        NaN          NaN

[5 rows x 68 columns]
  Variable Labels: 0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
33130    NaN
33131    NaN
33132    NaN
33133    NaN
33134    NaN
Name: var_labels, Length: 33135, dtype: object
  Value Labels: 0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
33130    NaN
33131    NaN
33132    NaN
33133    NaN
33134    NaN
Name: value_labels, Length: 33135, dtype: object


Year: year_2015
  File: REC0111_2015
    Data:                CASEID V000  V001  V002  V003  V004    V007    V008  V009  \
0        000102701  1  PE6   1.0  27.0   1.0   1.0  2015.0  1386.0   7.0
1        000104301  1  PE6   1.0  43.0   1.0   1.0  2015.0  1386.0   4.0
2        000104801  2  PE6   1.0  48.0   2.0   1.0  2015.0  1386.0   1.0
3        000104801  3  PE6   1.0  48.0   3.0   1.0  2015.0  1386.0  11.0
4        000105001  3  PE6   1.0  50.0   3.0   1.0  2015.0  1386.0   8.0

     V010  ...   V102  V120 V121 V122 V123 V124 V125          V127  V133  year
0  1985.0  ...  Urban   Yes   No   No   No   No   No    Earth/sand   8.0  2015
1  1974.0  ...  Urban   Yes  Yes  Yes   No   No   No  Cement/brick  14.0  2015
2  1980.0  ...  Urban   Yes  Yes  Yes  Yes  Yes  Yes  Cement/brick  11.0  2015
3  1999.0  ...  Urban   Yes  Yes  Yes  Yes  Yes  Yes  Cement/brick   9.0  2015
4  1993.0  ...  Urban   Yes  Yes  Yes   No   No   No  Cement/brick  14.0  2015

[5 rows x 23 columns]
    Variable Labels: {'CASEID': 'New Var Label: CASEID', 'V000': 'New Var Label: V000', 'V001': 'New Var Label: V001', 'V002': 'New Var Label: V002', 'V003': 'New Var Label: V003', 'V004': 'New Var Label: V004', 'V007': 'New Var Label: V007', 'V008': 'New Var Label: V008', 'V009': 'New Var Label: V009', 'V010': 'New Var Label: V010', 'V011': 'New Var Label: V011', 'V012': 'New Var Label: V012', 'V024': 'New Var Label: V024', 'V102': 'New Var Label: V102', 'V120': 'New Var Label: V120', 'V121': 'New Var Label: V121', 'V122': 'New Var Label: V122', 'V123': 'New Var Label: V123', 'V124': 'New Var Label: V124', 'V125': 'New Var Label: V125', 'V127': 'New Var Label: V127', 'V133': 'New Var Label: V133'}
    Value Labels: {'CASEID': 'New Value Label: CASEID', 'V000': 'New Value Label: V000', 'V001': 'New Value Label: V001', 'V002': 'New Value Label: V002', 'V003': 'New Value Label: V003', 'V004': 'New Value Label: V004', 'V007': 'New Value Label: V007', 'V008': 'New Value Label: V008', 'V009': 'New Value Label: V009', 'V010': 'New Value Label: V010', 'V011': 'New Value Label: V011', 'V012': 'New Value Label: V012', 'V024': 'New Value Label: V024', 'V102': 'New Value Label: V102', 'V120': 'New Value Label: V120', 'V121': 'New Value Label: V121', 'V122': 'New Value Label: V122', 'V123': 'New Value Label: V123', 'V124': 'New Value Label: V124', 'V125': 'New Value Label: V125', 'V127': 'New Value Label: V127', 'V133': 'New Value Label: V133'}
  File: RE223132_2015
    Data:                CASEID  V201  V218                 V301                V302  \
0        000102701  1   3.0   3.0  Knows modern method  Used modern method
1        000104301  1   2.0   2.0  Knows modern method  Used modern method
2        000104801  2   2.0   2.0  Knows modern method  Used modern method
3        000104801  3   0.0   0.0  Knows modern method          Never used
4        000105001  3   0.0   0.0  Knows modern method  Used modern method

  V323 V323A V325A                 V326                 V327  ...  \
0  NaN   NaN   NaN                  NaN                  NaN  ...
1  NaN   NaN   NaN       Hospital MINSA  Govt Clinical/Pharm  ...
2  NaN   NaN   NaN  Health center MINSA  Govt Clinical/Pharm  ...
3  NaN   NaN   NaN                  NaN                  NaN  ...
4  NaN   NaN   NaN                  NaN                  NaN  ...

                  V364         V367 V372 V372A           V375A V376 V376A  \
0   Non-user intend to  Wanted then  NaN   NaN     Not married  NaN   NaN
1  Using modern method  Wanted then  NaN   NaN             NaN  NaN   NaN
2  Using modern method          NaN  NaN   NaN             NaN  NaN   NaN
3   Non-user intend to          NaN  NaN   NaN  Not having sex  NaN   NaN
4   Non-user intend to          NaN  NaN   NaN  Infrequent sex  NaN   NaN

  V379 V380  year
0  NaN  NaN  2015
1  NaN  NaN  2015
2  NaN  NaN  2015
3  NaN  NaN  2015
4  NaN  NaN  2015

[5 rows x 26 columns]
    Variable Labels: {'CASEID': 'New Var Label: CASEID', 'V201': 'New Var Label: V201', 'V218': 'New Var Label: V218', 'V301': 'New Var Label: V301', 'V302': 'New Var Label: V302', 'V323': 'New Var Label: V323', 'V323A': 'New Var Label: V323A', 'V325A': 'New Var Label: V325A', 'V326': 'New Var Label: V326', 'V327': 'New Var Label: V327', 'V337': 'New Var Label: V337', 'V359': 'New Var Label: V359', 'V360': 'New Var Label: V360', 'V361': 'New Var Label: V361', 'V362': 'New Var Label: V362', 'V363': 'New Var Label: V363', 'V364': 'New Var Label: V364', 'V367': 'New Var Label: V367', 'V372': 'New Var Label: V372', 'V372A': 'New Var Label: V372A', 'V375A': 'New Var Label: V375A', 'V376': 'New Var Label: V376', 'V376A': 'New Var Label: V376A', 'V379': 'New Var Label: V379', 'V380': 'New Var Label: V380'}
    Value Labels: {'CASEID': 'New Value Label: CASEID', 'V201': 'New Value Label: V201', 'V218': 'New Value Label: V218', 'V301': 'New Value Label: V301', 'V302': 'New Value Label: V302', 'V323': 'New Value Label: V323', 'V323A': 'New Value Label: V323A', 'V325A': 'New Value Label: V325A', 'V326': 'New Value Label: V326', 'V327': 'New Value Label: V327', 'V337': 'New Value Label: V337', 'V359': 'New Value Label: V359', 'V360': 'New Value Label: V360', 'V361': 'New Value Label: V361', 'V362': 'New Value Label: V362', 'V363': 'New Value Label: V363', 'V364': 'New Value Label: V364', 'V367': 'New Value Label: V367', 'V372': 'New Value Label: V372', 'V372A': 'New Value Label: V372A', 'V375A': 'New Value Label: V375A', 'V376': 'New Value Label: V376', 'V376A': 'New Value Label: V376A', 'V379': 'New Value Label: V379', 'V380': 'New Value Label: V380'}
  File: RE516171_2015
    Data:                CASEID                 V501              V502  V503 V504 V505  \
0        063405501  6        Never married     Never married   NaN  NaN  NaN
1        000102701  1  Not living together  Formerly married  Once  NaN  NaN
2        000109001  1  Not living together  Formerly married  Once  NaN  NaN
3        000203201  7  Not living together  Formerly married  Once  NaN  NaN
4        000211901  6  Not living together  Formerly married  Once  NaN  NaN

  V506  V507    V508    V509            V510  V511  V512           V513  V525  \
0  NaN   NaN     NaN     NaN             NaN   NaN   NaN  Never married  18.0

7. Use `all_data` to append all the data sets. Store all data sets in a list using `for loop`. Then, use `pd.concat` to append all the data sets. Also, you must reset the index to have a good-looking data. This new object should be named as `endes_data_2015_2019`. **Hint: Use [this code](https://stackoverflow.com/questions/32444138/concatenate-a-list-of-pandas-dataframes-together)**

8. Store all the `var_labels` and `value_labels` in a dictionary named as `all_var_labels` and `all_value_labels`. The first keys should be the year for both dictionaries.Then, use them to generate new attributes for `endes_data_2015_2019`. These attributes should be named as `var_labels` and `value_labels`.  **Hint: Use [this link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=4d6de78e00e7001f16bf6473c2eb7ce24fb611cd&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f346436646537386530306537303031663136626636343733633265623763653234666236313163642f4c6563747572655f342f4c6563747572655f342e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_4%2FLecture_4.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=95#4.2.3.)**

9. Use `endes_data_2015_2019` data to generate a new object named `mean_key_vars` to find the mean of **total children ever born (V201)**, **Ideal number of children (V613)**, **Husbands education-single yrs (V715)**, and **Age at first marriage (V511)** by year and department **(V024)**. Name these columns as **mean_total_children, mean_ideal_children, mean_hb_yr_educ and mean_first_marriage**, respectively. **Hint: Use groupby and [this link](https://stackoverflow.com/questions/40901770/is-there-a-simple-way-to-change-a-column-of-yes-no-to-1-0-in-a-pandas-dataframe).**

10. Merge `mean_key_vars` with `endes_data_2015_2019`. Name this object `final_result`. **Hint: Use merge.**