In [17]:
import os
import pickle
import pandas as pd
import numpy as np
import urllib.request
import pyreadstat

### Pregunta 1
Import the REC0111.sav, RE223132.sav and RE516171.sav files and their variables and values labels from this path "../../_data/endes/2019". The name of imported files should be named as rec_1, rec_2 and rec_3 for files REC0111.sav, RE223132.sav and RE516171.sav respectively. The name of the variable and value labels should be var_labels1 and value_labels1 for rec1, var_labels2 and value_labels2 for rec2, and var_labels3 and value_labels3 for rec3

In [18]:
#we define the route where the files are located
p = '''../../_data/endes/2019'''
# we save the route of the three files

d1 = p+'''/REC0111.sav'''
d2 = p+'''/RE223132.sav'''
d3 = p+'''/RE516171.sav'''
#we import the sav files as pandas data frames (rec_x) and as an objetct with the metadata from the file (meta_x)\n"
rec_1,meta_1 = pyreadstat.read_sav(d1)
rec_2,meta_2 = pyreadstat.read_sav(d2)
rec_3,meta_3 = pyreadstat.read_sav(d3)

#we create dictionaries with the labels of variables and values of variables

var_labels1 = meta_1.column_names_to_labels
value_labels1 = meta_1.variable_value_labels

var_labels2 = meta_2.column_names_to_labels
value_labels2 = meta_2.variable_value_labels

var_labels3 = meta_3.column_names_to_labels
value_labels3 = meta_3.variable_value_labels

### Pregunta 2
Additonally, you should update the variables and value labels objects. They must have information only for the selected columns. The new dataframes should be name as rec1_1, rec2_1, and rec3_1. The new varible labels objects should be named as new_var_labels1, new_var_labels2, and new_var_labels3. The new value labels objects should be named as new_value_labels1, new_value_labels2, and new_value_labels3 Hint: Use the loc and column names to filter. Update the dictionary.

In [19]:
#We create a new data keeping all the cases for the indicated variables

rec1_1=rec_1.loc[:,['CASEID', 'V000', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008', 'V009', 'V010', 'V011', 'V012', 'V024', 'V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127'
, 'V133']]

rec2_1=rec_2.loc[:,['CASEID', 'V201', 'V218', 'V301', 'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327', 'V337', 'V359', 'V360', 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A', 'V375A', 'V376', 'V376A', 'V379', 'V380']]

rec3_1=rec_3.loc[:,['CASEID', 'V501', 'V502', 'V503', 'V504', 'V505', 'V506', 'V507', 'V508', 'V509', 'V510', 'V511', 'V512', 'V513', 'V525', 'V613', 'V714', 'V715']]

#We create a list with the names of the variables we are selecting to keep 
clave_seleccion1 = ['CASEID', 'V000', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008', 'V009', 'V010', 'V011', 'V012', 'V024', 'V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127'
, 'V133']

clave_seleccion2 = ['CASEID', 'V201', 'V218', 'V301', 'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327', 'V337', 'V359', 'V360', 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A', 'V375A', 'V376', 'V376A', 'V379', 'V380']

clave_seleccion3 = ['CASEID', 'V501', 'V502', 'V503', 'V504', 'V505', 'V506', 'V507', 'V508', 'V509', 'V510', 'V511', 'V512', 'V513', 'V525', 'V613', 'V714', 'V715']
#We create an empty dictionary to save the labels of the selectected variables
new_var_labels1 = {}
new_value_labels1 = {}

new_var_labels2 = {}
new_value_labels2 = {}

new_var_labels3 = {}
new_value_labels3 = {}

#We create the new labels dictionaries keeping only the keys that are in the clave_selection lists
for clave in var_labels1.keys():
    if clave in clave_seleccion1:
        new_var_labels1[clave] = var_labels1[clave]

for clave in value_labels1.keys():
    if clave in clave_seleccion1:
        new_value_labels1[clave] = value_labels1[clave]
        

for clave in var_labels2.keys():
    if clave in clave_seleccion2:
        new_var_labels2[clave] = var_labels2[clave]

for clave in value_labels2.keys():
    if clave in clave_seleccion2:
        new_value_labels2[clave] = value_labels2[clave]
        

for clave in var_labels3.keys():
    if clave in clave_seleccion3:
        new_var_labels3[clave] = var_labels3[clave]

for clave in value_labels3.keys():
    if clave in clave_seleccion3:
        new_value_labels3[clave] = value_labels3[clave]

## Pregunta 3

Generate a new column for rec1_1 named as year. It should be equal to 2019. Also, you must update this new variable for the var_labels dictionary. Generate a new key for new_var_labels1 and the value for this key should be "Year of the survey" Hint: Use loc and update method.

In [20]:
#we add the column "year to the data 
rec1_1.loc[:, "year"] = 2019
#and update the dictionary with year as a key 
new_var_labels1.update({"year": "Year of the survey"})

In [21]:
new_var_labels1.keys()

dict_keys(['CASEID', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008', 'V009', 'V010', 'V011', 'V012', 'V024', 'V000', 'V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127', 'V133', 'year'])

In [22]:
rec1_1.keys()

Index(['CASEID', 'V000', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008',
       'V009', 'V010', 'V011', 'V012', 'V024', 'V102', 'V120', 'V121', 'V122',
       'V123', 'V124', 'V125', 'V127', 'V133', 'year'],
      dtype='object')

## Pregunta 4

Merge rec1_1, rec2_1, and rec3_1 using CASEID. Name this new object as endes_2019

In [23]:
endes_2019 = pd.merge(left=rec1_1, right=rec2_1, how="inner", on="CASEID")
endes_2019 = pd.merge(left=endes_2019, right=rec3_1, how="inner", on="CASEID")

In [24]:
endes_2019.shape

(33311, 64)

In [25]:
endes_2019.head(10)

,CASEID,V000,V001,V002,V003,V004,V007,V008,V009,V010,...,V508,V509,V510,V511,V512,V513,V525,V613,V714,V715
0,000100201 2,PE6,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,2008.0,1297.0,1.0,21.0,11.0,3.0,17.0,2.0,1.0,11.0
1,000102801 2,PE6,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,1983.0,...,2011.0,1344.0,1.0,28.0,7.0,2.0,18.0,3.0,1.0,14.0
2,000102801 6,PE6,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,1970.0,...,1984.0,1016.0,5.0,14.0,34.0,7.0,14.0,0.0,0.0,6.0
3,000104801 2,PE6,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,1991.0,...,2009.0,1320.0,1.0,18.0,9.0,2.0,15.0,2.0,0.0,6.0
4,000113601 2,PE6,1.0,136.0,2.0,1.0,2019.0,1434.0,11.0,1988.0,...,2005.0,1272.0,1.0,17.0,13.0,3.0,15.0,2.0,1.0,16.0
5,000116701 1,PE6,1.0,167.0,1.0,1.0,2019.0,1434.0,6.0,2001.0,...,NaN,NaN,NaN,NaN,NaN,0.0,16.0,2.0,0.0,NaN
6,000119101 1,PE6,1.0,191.0,1.0,1.0,2019.0,1434.0,9.0,1995.0,...,2013.0,1364.0,1.0,17.0,5.0,2.0,17.0,2.0,1.0,13.0
7,000120701 2,PE6,1.0,207.0,2.0,1.0,2019.0,1434.0,8.0,1984.0,...,2002.0,1230.0,1.0,17.0,17.0,4.0,17.0,2.0,1.0,14.0
8,000200301 3,PE6,2.0,3.0,3.0,2.0,2019.0,1432.0,12.0,1987.0,...,2011.0,1338.0,1.0,23.0,7.0,2.0,20.0,2.0,0.0,16.0
9,000203001 2,PE6,2.0,30.0,2.0,2.0,2019.0,1432.0,5.0,1990.0,...,2013.0,1357.0,1.0,22.0,6.0,2.0,19.0,3.0,0.0,15.0

In [26]:
### para probar algunas NaN  rec2_1.loc[rec2_1["CASEID"].str.contains("000116701")]
endes_2019.keys()

Index(['CASEID', 'V000', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008',
       'V009', 'V010', 'V011', 'V012', 'V024', 'V102', 'V120', 'V121', 'V122',
       'V123', 'V124', 'V125', 'V127', 'V133', 'year', 'V201', 'V218', 'V301',
       'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327', 'V337', 'V359',
       'V360', 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A',
       'V375A', 'V376', 'V376A', 'V379', 'V380', 'V501', 'V502', 'V503',
       'V504', 'V505', 'V506', 'V507', 'V508', 'V509', 'V510', 'V511', 'V512',
       'V513', 'V525', 'V613', 'V714', 'V715'],
      dtype='object')

### Pregunta 5

Unify all the new_var_labels in one object and new_value_labels in another one object. Name these two objects as var_labels and value_labels. Use them to generate new attributes for endes_2019. These attributes should be named as var_labels and value_labels. Hint: Use update method

In [27]:
lista_keys=list(endes_2019.keys())

In [28]:
var_labels = {}
value_labels = {}


for clave in var_labels1.keys():
    if clave in lista_keys:
        var_labels[clave] = var_labels1[clave]

for clave in value_labels1.keys():
    if clave in lista_keys:
        value_labels[clave] = value_labels1[clave]
        
for clave in var_labels2.keys():
    if clave in lista_keys:
        var_labels[clave] = var_labels2[clave]

for clave in value_labels2.keys():
    if clave in lista_keys:
        value_labels[clave] = value_labels2[clave]
        
for clave in var_labels3.keys():
    if clave in lista_keys:
        var_labels[clave] = var_labels3[clave]

for clave in value_labels3.keys():
    if clave in lista_keys:
        value_labels[clave] = value_labels3[clave]
        
print(var_labels.keys())
print(value_labels.keys())

dict_keys(['CASEID', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008', 'V009', 'V010', 'V011', 'V012', 'V024', 'V000', 'V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127', 'V133', 'V201', 'V218', 'V301', 'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327', 'V337', 'V359', 'V360', 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A', 'V375A', 'V376', 'V376A', 'V379', 'V380', 'V501', 'V502', 'V503', 'V504', 'V505', 'V506', 'V507', 'V508', 'V509', 'V510', 'V511', 'V512', 'V513', 'V525', 'V613', 'V714', 'V715'])
dict_keys(['V024', 'V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127', 'V133', 'V301', 'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327', 'V337', 'V359', 'V360', 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A', 'V375A', 'V376', 'V376A', 'V379', 'V380', 'V501', 'V502', 'V503', 'V504', 'V505', 'V506', 'V510', 'V513', 'V525', 'V613', 'V714', 'V715'])

In [29]:
## Pregunta 4

#Merge rec1_1, rec2_1, and rec3_1 using CASEID. Name this new object as endes_2019

endes_2019 = pd.merge(left=rec1_1, right=rec2_1, how="inner", on="CASEID")
endes_2019 = pd.merge(left=endes_2019, right=rec3_1, how="inner", on="CASEID")


endes_2019.shape

endes_2019.head(10)

### para probar algunas NaN  rec2_1.loc[rec2_1["CASEID"].str.contains("000116701")]

endes_2019.keys()

### Pregunta 5

#Unify all the new_var_labels in one object and new_value_labels in another one object. Name these two objects as var_labels and value_labels. Use them to generate new attributes for endes_2019. These attributes should be named as var_labels and value_labels. Hint: Use update method

lista_keys=list(endes_2019.keys())

var_labels = {}
value_labels = {}

### We create new dictionaries of tags, mantaining as keys only variables from list lista_keys. Because it's SPSS format, we need to bring tags from SPSS
for clave in var_labels1.keys():
    if clave in lista_keys:
        var_labels[clave] = var_labels1[clave]

for clave in value_labels1.keys():
    if clave in lista_keys:
        value_labels[clave] = value_labels1[clave]
        
for clave in var_labels2.keys():
    if clave in lista_keys:
        var_labels[clave] = var_labels2[clave]

for clave in value_labels2.keys():
    if clave in lista_keys:
        value_labels[clave] = value_labels2[clave]
        
for clave in var_labels3.keys():
    if clave in lista_keys:
        var_labels[clave] = var_labels3[clave]

for clave in value_labels3.keys():
    if clave in lista_keys:
        value_labels[clave] = value_labels3[clave]
        
print(var_labels.keys())
print(value_labels.keys())

dict_keys(['CASEID', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008', 'V009', 'V010', 'V011', 'V012', 'V024', 'V000', 'V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127', 'V133', 'V201', 'V218', 'V301', 'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327', 'V337', 'V359', 'V360', 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A', 'V375A', 'V376', 'V376A', 'V379', 'V380', 'V501', 'V502', 'V503', 'V504', 'V505', 'V506', 'V507', 'V508', 'V509', 'V510', 'V511', 'V512', 'V513', 'V525', 'V613', 'V714', 'V715'])
dict_keys(['V024', 'V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127', 'V133', 'V301', 'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327', 'V337', 'V359', 'V360', 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A', 'V375A', 'V376', 'V376A', 'V379', 'V380', 'V501', 'V502', 'V503', 'V504', 'V505', 'V506', 'V510', 'V513', 'V525', 'V613', 'V714', 'V715'])